### ISSUE TITLE
New Ubuntu 15.10 Instances

### ISSUE THREAD

**Issue by bovorns** [tankitty/ar-bro#23]
When created new instance with Ubuntu 15.10, The Interface only have loop back interface

**Comment by tan-kitty** [comment]
Instance ID please

**Comment by bovorns** [comment]
I removed already and re-create new instance with Ubuntu 14.xx instead

**Comment by tan-kitty** [comment]
anything is OK ?

**Comment by bovorns** [comment]
Yes. It's OK now. But I repeated for Ubuntu 15.10 still have the same problem.

Now I use Ubuntu 14.xx

**Comment by tan-kitty** [comment]
give me your email address please

**Comment by bovorns** [comment]
bovorn at icloud dot com

**Comment by blisscs** [comment]
Having the same issue.
My instance name is cswebdocker.ar-bro.net
please check for me.

Thank you
Dev.

**Comment by tan-kitty** [comment]
the interface name changed from eth0 to -> ensX 

# ifconfig -a

and edit interfaces file
vi /etc/network/interfaces    <--- replace eth0 to ensX (from ifconfig -a)

**Comment by blisscs** [comment]
It's fix now.
I think this issue is in ubuntu original 15 image. Probably has to fix it in the image original image also.
Please see.

Thank you @tankitty

**Comment by tan-kitty** [comment]
Welcome @blisscs   : )
