### ISSUE TITLE
After create instance menu not display all

### ISSUE THREAD

**Issue by IkuraRamen** [tankitty/ar-bro#4]
After create instance menu not display all.

![2015-12-06 16_21_00-ar-bro cloud platform](https://cloud.githubusercontent.com/assets/1430323/11616713/51ed6604-9c37-11e5-8d64-68cfbdac4b08.jpg)

After refresh.

![2015-12-06 16_21_17-ar-bro cloud platform](https://cloud.githubusercontent.com/assets/1430323/11616716/5eaa2184-9c37-11e5-89e6-43d8c099a046.jpg)

**Comment by chavalitp** [comment]
Thank you for a feedback, SlayerBuu :)

Access and Power menus can be accessed as soon as the instance is powered on.
Settings and Destroy can be accessed after the instance IP address is assigned by the system.
We should show it more clearly that the instance IP is not assigned and other menu will be visible later.
