### ISSUE TITLE
After create I don't know username and password

### ISSUE THREAD

**Issue by IkuraRamen** [tankitty/ar-bro#5]
After create I don't know username and password to access console.
I just see in menu settings.
I must refresh page to see menu settings because after create Instance not show menu settings.
Maybe you should send username and password to email or show after create Instance.

**Comment by chavalitp** [comment]
Thank you for your feedback, SlayerBuu :)
1. We're now showing username and password above console button.
2. Access and Power menu can be accessed as soon as instance is powered on.
   But other menus will not be visible until an instance IP address is assigned by the system.

**Comment by blisscs** [comment]
It's possible to also email the password through email also after the server creation.
This would be a nice feature. 

Dev
