### ISSUE TITLE
Power off แล้วไปสวรรค์

### ISSUE THREAD

**Issue by goragodwiriya** [tankitty/ar-bro#7]
150.107.29.129 Power off แล้วไปสวรรค์เลย

CentOS 7

ตอนที่ลง CentOS 6 ราบรื่นกว่านะ

**Comment by goragodwiriya** [comment]
ขั้นตอนการ destroy สั้นไปหน่อยมั้ย น่าจะมีการยืนยันมากขั้นตอนกว่านี้หน่อย เช่น ต้องกรอกชื่อ hostname ก่อนจะลบ

**Comment by chavalitp** [comment]
ขอบคุณสำหรับคำแนะนำครับ :)

**Comment by chavalitp** [comment]
เพิ่มการยืนยันด้วย hostname ก่อนลบแล้วนะครับ
